### ISSUE TITLE
IndexError for "print_available_languages()" function

### ISSUE THREAD

**Issue by ppostnov** [iwpnd/toponym#7]
Please check on your side a proper work for this function. When I trying to get a list of available languages I receiving the index error: list index out of range 

seems that dictionary in "settings.py" is correct on my local side:

![image](https://user-images.githubusercontent.com/10743400/68312652-6ec1b500-00c4-11ea-8235-2e80197cfc62.png)

or I should to check "TOPODICT_DIR" also ?

**Comment by iwpnd** [comment]
Im not able to replicate it, but I would assume that it comes down to the way you install and import toponym. Can you provide some more info on how you installed/import it?

**Comment by ppostnov** [comment]
I have reinstalled the package and seems that an error is gone:
![image](https://user-images.githubusercontent.com/10743400/68368342-e9341880-0148-11ea-9b7c-daf52500e77e.png)
