### ISSUE TITLE
Mismatch in the number of lang codes and languages

### ISSUE THREAD

**Issue by ppostnov** [iwpnd/toponym#8]
For current solution we always should keep the same number of lang codes in "resource" path and in "LANGUAGE_DICT" dictionary.

True case:
![image](https://user-images.githubusercontent.com/10743400/68382593-1989b000-0165-11ea-818b-7a615d97e81a.png)

False case:
![image](https://user-images.githubusercontent.com/10743400/68382725-5a81c480-0165-11ea-85ef-e30e3056df5f.png)

**Comment by ppostnov** [comment]
or add some exception

**Comment by ppostnov** [comment]
I think that it was the reason my previous issue #7

**Comment by iwpnd** [comment]
fixed in current version
